### ISSUE TITLE
Typo in alert-dismissible

### ISSUE THREAD

**Issue by tuhinkarmakar** [webBoxio/atom-bootstrap3#27]
There is a typo in the word "dismissible" in alert-dismissible autocompletion entry. It should be **"dismissible"** not **"dismissable".**

![alert-bug](https://cloud.githubusercontent.com/assets/11135104/8679905/4991a2dc-2a7b-11e5-83f7-4a3e8931fc59.png)

**Comment by peterblazejewicz** [comment]
Actually that is a correct label, but it should be phased out after BS 3.2.0:
https://github.com/twbs/bootstrap/blob/3487898a6af8c1d5b12f7b040d30e71b19e34923/less/alerts.less#L42-L43
